// AUTO-GENERATED by upload_images.py. Do not edit by hand.
// Maps service slugs to CDN-hosted hero images uploaded from Dropbox.

import img_fertilitet_assistert_befruktning from "@/assets/services/fertilitet-assistert-befruktning.jpg.asset.json";
import img_fertilitet_donorbehandling from "@/assets/services/fertilitet-donorbehandling.jpg.asset.json";
import img_fertilitet_eggfrys from "@/assets/services/fertilitet-eggfrys.jpg.asset.json";
import img_fertilitet_fertilitetsteamet from "@/assets/services/fertilitet-fertilitetsteamet.jpg.asset.json";
import img_fertilitet_fertilitetsutredning from "@/assets/services/fertilitet-fertilitetsutredning.jpg.asset.json";
import img_fertilitet_hero from "@/assets/services/fertilitet-hero.jpg.asset.json";
import img_fertilitet_hysteroskopi from "@/assets/services/fertilitet-hysteroskopi.jpg.asset.json";
import img_fertilitet_infertilitet from "@/assets/services/fertilitet-infertilitet.jpg.asset.json";
import img_fertilitet_ivf from "@/assets/services/fertilitet-ivf.jpg.asset.json";
import img_fertilitet_saedanalyse from "@/assets/services/fertilitet-saedanalyse.jpg.asset.json";
import img_flere_areknutebehandling from "@/assets/services/flere-areknutebehandling.jpg.asset.json";
import img_flere_endokrinologi from "@/assets/services/flere-endokrinologi.jpg.asset.json";
import img_flere_ernaeringsfysologi from "@/assets/services/flere-ernaeringsfysologi.jpg.asset.json";
import img_flere_gastrokirurgi from "@/assets/services/flere-gastrokirurgi.jpg.asset.json";
import img_flere_hero from "@/assets/services/flere-hero.jpg.asset.json";
import img_flere_hudhelse from "@/assets/services/flere-hudhelse.jpg.asset.json";
import img_flere_hudlege from "@/assets/services/flere-hudlege.jpg.asset.json";
import img_flere_osteopati from "@/assets/services/flere-osteopati.jpg.asset.json";
import img_flere_overvektskirurgi from "@/assets/services/flere-overvektskirurgi.jpg.asset.json";
import img_flere_plastikkirurgi from "@/assets/services/flere-plastikkirurgi.jpg.asset.json";
import img_flere_psykologi from "@/assets/services/flere-psykologi.jpg.asset.json";
import img_flere_revmatologi from "@/assets/services/flere-revmatologi.jpg.asset.json";
import img_flere_robotkirurgi from "@/assets/services/flere-robotkirurgi.jpg.asset.json";
import img_flere_sexologi from "@/assets/services/flere-sexologi.jpg.asset.json";
import img_graviditet_fosterdiagnostikk from "@/assets/services/graviditet-fosterdiagnostikk.jpg.asset.json";
import img_graviditet_hero from "@/assets/services/graviditet-hero.jpg.asset.json";
import img_graviditet_nipt from "@/assets/services/graviditet-nipt.jpg.asset.json";
import img_graviditet_svangerskapsteam from "@/assets/services/graviditet-svangerskapsteam.jpg.asset.json";
import img_graviditet_ultralyd from "@/assets/services/graviditet-ultralyd.jpg.asset.json";
import img_gynekologi_blodningsforstyrrelser from "@/assets/services/gynekologi-blodningsforstyrrelser.jpg.asset.json";
import img_gynekologi_celleforandringer from "@/assets/services/gynekologi-celleforandringer.jpg.asset.json";
import img_gynekologi_cyster_pa_eggstokkene from "@/assets/services/gynekologi-cyster-pa-eggstokkene.jpg.asset.json";
import img_gynekologi_endometriose from "@/assets/services/gynekologi-endometriose.jpg.asset.json";
import img_gynekologi_fjerne_livmor from "@/assets/services/gynekologi-fjerne-livmor.jpg.asset.json";
import img_gynekologi_graviditet from "@/assets/services/gynekologi-graviditet.jpg.asset.json";
import img_gynekologi_gynekologisk_kirurgi from "@/assets/services/gynekologi-gynekologisk-kirurgi.jpg.asset.json";
import img_gynekologi_gynekologisk_undersokelse from "@/assets/services/gynekologi-gynekologisk-undersokelse.jpg.asset.json";
import img_gynekologi_hero from "@/assets/services/gynekologi-hero.jpg.asset.json";
import img_gynekologi_hormonforstyrrelser from "@/assets/services/gynekologi-hormonforstyrrelser.jpg.asset.json";
import img_gynekologi_labiaplastikk from "@/assets/services/gynekologi-labiaplastikk.jpg.asset.json";
import img_gynekologi_overgangsalder from "@/assets/services/gynekologi-overgangsalder.jpg.asset.json";
import img_gynekologi_robotkirurgi from "@/assets/services/gynekologi-robotkirurgi.jpg.asset.json";
import img_gynekologi_spontanabort from "@/assets/services/gynekologi-spontanabort.jpg.asset.json";
import img_gynekologi_tverrfaglig_team from "@/assets/services/gynekologi-tverrfaglig-team.jpg.asset.json";
import img_gynekologi_urinlekkasje from "@/assets/services/gynekologi-urinlekkasje.jpg.asset.json";
import img_gynekologi_vaginalt_fremfall from "@/assets/services/gynekologi-vaginalt-fremfall.jpg.asset.json";
import img_gynekologi_vulvalidelser from "@/assets/services/gynekologi-vulvalidelser.jpg.asset.json";
import img_ortopedi_fot_og_ankel from "@/assets/services/ortopedi-fot-og-ankel.jpg.asset.json";
import img_ortopedi_hand_og_albue from "@/assets/services/ortopedi-hand-og-albue.jpg.asset.json";
import img_ortopedi_hero from "@/assets/services/ortopedi-hero.jpg.asset.json";
import img_ortopedi_hofte from "@/assets/services/ortopedi-hofte.jpg.asset.json";
import img_ortopedi_kne from "@/assets/services/ortopedi-kne.jpg.asset.json";
import img_ortopedi_skulder from "@/assets/services/ortopedi-skulder.jpg.asset.json";
import img_urologi_blaere_og_urinveier from "@/assets/services/urologi-blaere-og-urinveier.jpg.asset.json";
import img_urologi_forhud from "@/assets/services/urologi-forhud.jpg.asset.json";
import img_urologi_hero from "@/assets/services/urologi-hero.jpg.asset.json";
import img_urologi_mannlig_infertilitet from "@/assets/services/urologi-mannlig-infertilitet.jpg.asset.json";
import img_urologi_nyrer from "@/assets/services/urologi-nyrer.jpg.asset.json";
import img_urologi_prostata from "@/assets/services/urologi-prostata.jpg.asset.json";
import img_urologi_refertilisering from "@/assets/services/urologi-refertilisering.jpg.asset.json";
import img_urologi_robotkirurgi from "@/assets/services/urologi-robotkirurgi.jpg.asset.json";
import img_urologi_sterilisering from "@/assets/services/urologi-sterilisering.jpg.asset.json";
import img_urologi_testikler_og_pung from "@/assets/services/urologi-testikler-og-pung.jpg.asset.json";

export const serviceImageBySlug: Record<string, string> = {
  "fertilitet-assistert-befruktning": img_fertilitet_assistert_befruktning.url,
  "fertilitet-donorbehandling": img_fertilitet_donorbehandling.url,
  "fertilitet-eggfrys": img_fertilitet_eggfrys.url,
  "fertilitet-fertilitetsteamet": img_fertilitet_fertilitetsteamet.url,
  "fertilitet-fertilitetsutredning": img_fertilitet_fertilitetsutredning.url,
  "fertilitet-hero": img_fertilitet_hero.url,
  "fertilitet-hysteroskopi": img_fertilitet_hysteroskopi.url,
  "fertilitet-infertilitet": img_fertilitet_infertilitet.url,
  "fertilitet-ivf": img_fertilitet_ivf.url,
  "fertilitet-saedanalyse": img_fertilitet_saedanalyse.url,
  "flere-areknutebehandling": img_flere_areknutebehandling.url,
  "flere-endokrinologi": img_flere_endokrinologi.url,
  "flere-ernaeringsfysologi": img_flere_ernaeringsfysologi.url,
  "flere-gastrokirurgi": img_flere_gastrokirurgi.url,
  "flere-hero": img_flere_hero.url,
  "flere-hudhelse": img_flere_hudhelse.url,
  "flere-hudlege": img_flere_hudlege.url,
  "flere-osteopati": img_flere_osteopati.url,
  "flere-overvektskirurgi": img_flere_overvektskirurgi.url,
  "flere-plastikkirurgi": img_flere_plastikkirurgi.url,
  "flere-psykologi": img_flere_psykologi.url,
  "flere-revmatologi": img_flere_revmatologi.url,
  "flere-robotkirurgi": img_flere_robotkirurgi.url,
  "flere-sexologi": img_flere_sexologi.url,
  "graviditet-fosterdiagnostikk": img_graviditet_fosterdiagnostikk.url,
  "graviditet-hero": img_graviditet_hero.url,
  "graviditet-nipt": img_graviditet_nipt.url,
  "graviditet-svangerskapsteam": img_graviditet_svangerskapsteam.url,
  "graviditet-ultralyd": img_graviditet_ultralyd.url,
  "gynekologi-blodningsforstyrrelser": img_gynekologi_blodningsforstyrrelser.url,
  "gynekologi-celleforandringer": img_gynekologi_celleforandringer.url,
  "gynekologi-cyster-pa-eggstokkene": img_gynekologi_cyster_pa_eggstokkene.url,
  "gynekologi-endometriose": img_gynekologi_endometriose.url,
  "gynekologi-fjerne-livmor": img_gynekologi_fjerne_livmor.url,
  "gynekologi-graviditet": img_gynekologi_graviditet.url,
  "gynekologi-gynekologisk-kirurgi": img_gynekologi_gynekologisk_kirurgi.url,
  "gynekologi-gynekologisk-undersokelse": img_gynekologi_gynekologisk_undersokelse.url,
  "gynekologi-hero": img_gynekologi_hero.url,
  "gynekologi-hormonforstyrrelser": img_gynekologi_hormonforstyrrelser.url,
  "gynekologi-labiaplastikk": img_gynekologi_labiaplastikk.url,
  "gynekologi-overgangsalder": img_gynekologi_overgangsalder.url,
  "gynekologi-robotkirurgi": img_gynekologi_robotkirurgi.url,
  "gynekologi-spontanabort": img_gynekologi_spontanabort.url,
  "gynekologi-tverrfaglig-team": img_gynekologi_tverrfaglig_team.url,
  "gynekologi-urinlekkasje": img_gynekologi_urinlekkasje.url,
  "gynekologi-vaginalt-fremfall": img_gynekologi_vaginalt_fremfall.url,
  "gynekologi-vulvalidelser": img_gynekologi_vulvalidelser.url,
  "ortopedi-fot-og-ankel": img_ortopedi_fot_og_ankel.url,
  "ortopedi-hand-og-albue": img_ortopedi_hand_og_albue.url,
  "ortopedi-hero": img_ortopedi_hero.url,
  "ortopedi-hofte": img_ortopedi_hofte.url,
  "ortopedi-kne": img_ortopedi_kne.url,
  "ortopedi-skulder": img_ortopedi_skulder.url,
  "urologi-blaere-og-urinveier": img_urologi_blaere_og_urinveier.url,
  "urologi-forhud": img_urologi_forhud.url,
  "urologi-hero": img_urologi_hero.url,
  "urologi-mannlig-infertilitet": img_urologi_mannlig_infertilitet.url,
  "urologi-nyrer": img_urologi_nyrer.url,
  "urologi-prostata": img_urologi_prostata.url,
  "urologi-refertilisering": img_urologi_refertilisering.url,
  "urologi-robotkirurgi": img_urologi_robotkirurgi.url,
  "urologi-sterilisering": img_urologi_sterilisering.url,
  "urologi-testikler-og-pung": img_urologi_testikler_og_pung.url,
};

/**
 * Slug aliases — when categoryId+subId routes use a different shape than the
 * uploaded image slugs (e.g. /behandlinger/flere-fagomrader/* uses prefix
 * "flere-fagomrader-" while images use "flere-"), map them here.
 */
const ALIAS: Record<string, string> = {
  // category renames
  "flere-fagomrader": "flere",
};

/**
 * Per-(category,subId) aliases when route slugs differ from image slugs.
 * Key: `${categoryId}/${subId}` (route shape). Value: target subId in images.
 */
const SUB_ALIAS: Record<string, string> = {
  // gynekologi
  "gynekologi/tverrfaglig": "tverrfaglig-team",
  "gynekologi/undersokelse": "gynekologisk-undersokelse",
  "gynekologi/kirurgi": "gynekologisk-kirurgi",
  "gynekologi/vaginale-fremfall": "vaginalt-fremfall",
  "gynekologi/cyster": "cyster-pa-eggstokkene",
  "gynekologi/hysteroskopi": "gynekologisk-kirurgi", // no dedicated image
  // NIPT lives in graviditet image set
  // gynekologi pages without dedicated images — reuse closest relevant photo
  "gynekologi/pcos": "hormonforstyrrelser",
  "gynekologi/pms-pmdd": "hormonforstyrrelser",
  // urologi
  "urologi/blaere": "blaere-og-urinveier",
  "urologi/infertilitet": "mannlig-infertilitet",
  "urologi/testikler": "testikler-og-pung",
  // fertilitet
  "fertilitet/teamet": "fertilitetsteamet",
  // ortopedi
  "ortopedi/fot-ankel": "fot-og-ankel",
  "ortopedi/hand-albue": "hand-og-albue",
  // flere-fagomrader (category aliased to "flere")
  "flere-fagomrader/areknuter": "areknutebehandling",
  "flere-fagomrader/ernaringsfysiolog": "ernaeringsfysologi",
  "flere-fagomrader/ernaeringsfysiolog": "ernaeringsfysologi",
  "flere-fagomrader/hudbehandlinger": "hudhelse",
  "flere-fagomrader/behandlingsutstyr": "hudhelse",
  "flere-fagomrader/hudpleieprodukter": "hudhelse",
  "flere-fagomrader/sleeve-gastrektomi": "overvektskirurgi",
  // fertilitet
  "fertilitet/assistert-befruktning-for-par-og-single": "assistert-befruktning",
  "fertilitet/assistert-befruktning-par-single": "assistert-befruktning",
};

/**
 * Cross-category subId aliases — when an image lives under a different
 * category than the route. Looked up after the in-category SUB_ALIAS miss.
 * Value is the full image slug (e.g. "graviditet-nipt").
 */
const CROSS_CATEGORY_ALIAS: Record<string, string> = {
  "gynekologi/fostermedisin": "graviditet-fosterdiagnostikk",
  "gynekologi/fodselsskader": "graviditet-svangerskapsteam",
};

function normalize(categoryId: string, subId?: string): string {
  const cat = ALIAS[categoryId] ?? categoryId;
  const sub = subId ? (SUB_ALIAS[`${categoryId}/${subId}`] ?? subId) : undefined;
  return sub ? `${cat}-${sub}` : `${cat}-hero`;
}

/**
 * Return the CDN URL for a service hero image given the route params.
 * Falls back to the category hero image, then undefined.
 */
export function getServiceImage(categoryId: string, subId?: string): string | undefined {
  if (subId) {
    const cross = CROSS_CATEGORY_ALIAS[`${categoryId}/${subId}`];
    if (cross && serviceImageBySlug[cross]) return serviceImageBySlug[cross];
  }
  const exact = serviceImageBySlug[normalize(categoryId, subId)];
  if (exact) return exact;
  // try common slug rewrites
  if (subId) {
    const alt = subId
      .replace(/oe/g, "o")
      .replace(/ae/g, "a")
      .replace(/aa/g, "a");
    const altKey = `${ALIAS[categoryId] ?? categoryId}-${alt}`;
    if (serviceImageBySlug[altKey]) return serviceImageBySlug[altKey];
  }
  // fallback: category hero
  return serviceImageBySlug[`${ALIAS[categoryId] ?? categoryId}-hero`];
}

/**
 * Like getServiceImage, but only returns a URL when a dedicated image
 * exists for the (category, subId) pair. Returns undefined when only the
 * category-level hero would match. Used to override hardcoded fallbacks
 * in static content.
 */
export function getDedicatedServiceImage(categoryId: string, subId?: string): string | undefined {
  if (!subId) return undefined;
  const cross = CROSS_CATEGORY_ALIAS[`${categoryId}/${subId}`];
  if (cross && serviceImageBySlug[cross]) return serviceImageBySlug[cross];
  const exact = serviceImageBySlug[normalize(categoryId, subId)];
  if (exact) return exact;
  const alt = subId
    .replace(/oe/g, "o")
    .replace(/ae/g, "a")
    .replace(/aa/g, "a");
  const altKey = `${ALIAS[categoryId] ?? categoryId}-${alt}`;
  return serviceImageBySlug[altKey];
}

export function getCategoryHeroImage(categoryId: string): string | undefined {
  return serviceImageBySlug[`${ALIAS[categoryId] ?? categoryId}-hero`];
}

/**
 * Single source of truth for subpage hero images, resolved from a
 * /behandlinger/<category>/<sub> href. Use on landing pages so service cards
 * show exactly the same image as the subpage hero.
 */
export function getServiceImageFromHref(href: string): string | undefined {
  const m = href.match(/^\/behandlinger\/([^/?#]+)(?:\/([^/?#]+))?/);
  if (!m) return undefined;
  return getServiceImage(m[1], m[2]);
}
