// AUTO-GENERATED by upload_images.py. Do not edit by hand.
// Maps service slugs to CDN-hosted hero images uploaded from Dropbox.

import img_fertilitet_assistert_befruktning from "@/assets/services/fertilitet-assistert-befruktning.jpg.asset.json";
import img_fertilitet_donorbehandling from "@/assets/services/fertilitet-donorbehandling.jpg.asset.json";
import img_fertilitet_eggfrys from "@/assets/services/fertilitet-eggfrys.jpg.asset.json";
import img_fertilitet_fertilitetsutredning from "@/assets/services/fertilitet-fertilitetsutredning.jpg.asset.json";
import img_fertilitet_hero from "@/assets/services/fertilitet-hero.jpg.asset.json";
import img_fertilitet_hysteroskopi from "@/assets/services/fertilitet-hysteroskopi.jpg.asset.json";
import img_fertilitet_infertilitet from "@/assets/services/fertilitet-infertilitet.jpg.asset.json";
import img_fertilitet_ivf from "@/assets/services/fertilitet-ivf.jpg.asset.json";
import img_fertilitet_saedanalyse from "@/assets/services/fertilitet-saedanalyse.jpg.asset.json";
import img_flere_areknutebehandling from "@/assets/services/flere-areknutebehandling.jpg.asset.json";
import img_flere_endokrinologi from "@/assets/services/flere-endokrinologi.jpg.asset.json";
import img_flere_ernaeringsfysologi from "@/assets/services/flere-ernaeringsfysologi.jpg.asset.json";
import img_flere_gastrokirurgi from "@/assets/services/gastrokirurgi.png.asset.json";
import img_flere_hero from "@/assets/services/flere-hero.jpg.asset.json";
import img_flere_hudhelse from "@/assets/hudhelse/hudhelse.png.asset.json";
import img_flere_hudbehandlinger from "@/assets/hudhelse/hudbehandlinger.webp.asset.json";
import img_flere_hudpleieprodukter from "@/assets/hudhelse/hudprodukter.webp.asset.json";
import img_flere_behandlingsutstyr from "@/assets/hudhelse/behandlingsutstyr.webp.asset.json";
import img_flere_hudlege from "@/assets/services/flere-hudlege.jpg.asset.json";
import img_flere_osteopati from "@/assets/services/flere-osteopati.jpg.asset.json";
import img_flere_overvektskirurgi from "@/assets/gastro/overvektskirurgi.png.asset.json";
import img_flere_brokkoperasjon from "@/assets/gastro/brokkoperasjon.png.asset.json";
import img_flere_hemorroider from "@/assets/gastro/hemoroider-rektocele.png.asset.json";
import img_flere_plastikkirurgi from "@/assets/services/flere-plastikkirurgi.jpg.asset.json";
import img_flere_psykologi from "@/assets/services/flere-psykologi.jpg.asset.json";
import img_flere_revmatologi from "@/assets/services/flere-revmatologi.jpg.asset.json";
import img_flere_robotkirurgi from "@/assets/graviditet/robotassistert-kirurgi.png.asset.json";
import img_flere_sexologi from "@/assets/services/flere-sexologi.jpg.asset.json";
import img_graviditet_fosterdiagnostikk from "@/assets/graviditet/fosterdiagnostikk.png.asset.json";
import img_graviditet_fostermedisin from "@/assets/graviditet/fostermedisin.png.asset.json";
import img_graviditet_hero from "@/assets/graviditet/graviditet-hero.png.asset.json";
import img_graviditet_nipt from "@/assets/graviditet/nipt.png.asset.json";
import img_graviditet_svangerskapsteam from "@/assets/graviditet/svangerskapsteam.png.asset.json";
import img_graviditet_ultralyd from "@/assets/graviditet/ultralyd.png.asset.json";
import img_graviditet_6_ukerskontroll from "@/assets/graviditet/6-ukerskontroll.jpg.asset.json";
import img_gynekologi_blodningsforstyrrelser from "@/assets/services/gynekologi-blodningsforstyrrelser.jpg.asset.json";
import img_gynekologi_celleforandringer from "@/assets/services/gynekologi-celleforandringer.jpg.asset.json";
import img_gynekologi_cyster_pa_eggstokkene from "@/assets/services/gynekologi-cyster-pa-eggstokkene.jpg.asset.json";
import img_gynekologi_endometriose from "@/assets/services/gynekologi-endometriose.jpg.asset.json";
import img_gynekologi_fjerne_livmor from "@/assets/services/gynekologi-fjerne-livmor.jpg.asset.json";
import img_gynekologi_graviditet from "@/assets/services/gynekologi-graviditet.jpg.asset.json";
import img_gynekologi_gynekologisk_kirurgi from "@/assets/gynekologi/gynekologisk-kirurgi.png.asset.json";
import img_gynekologi_gynekologisk_undersokelse from "@/assets/services/gynekologi-gynekologisk-undersokelse.jpg.asset.json";
import img_gynekologi_hysteroskopi from "@/assets/gynekologi/hysteroskopi.png.asset.json";
import img_gynekologi_fodselsskader from "@/assets/gynekologi/fodselsskader-ny.png.asset.json";
import img_gynekologi_hero from "@/assets/services/gynekologi-hero.jpg.asset.json";
import img_gynekologi_hormonforstyrrelser from "@/assets/services/gynekologi-hormonforstyrrelser.jpg.asset.json";
import img_gynekologi_labiaplastikk from "@/assets/services/gynekologi-labiaplastikk.jpg.asset.json";
import img_gynekologi_overgangsalder from "@/assets/services/gynekologi-overgangsalder.jpg.asset.json";
import img_gynekologi_robotkirurgi from "@/assets/services/gynekologi-robotkirurgi.jpg.asset.json";
import img_gynekologi_spontanabort from "@/assets/services/gynekologi-spontanabort.jpg.asset.json";
import img_gynekologi_tverrfaglig_team from "@/assets/services/gynekologi-tverrfaglig-team.jpg.asset.json";
import img_gynekologi_urinlekkasje from "@/assets/services/gynekologi-urinlekkasje.jpg.asset.json";
import img_gynekologi_vaginalt_fremfall from "@/assets/services/gynekologi-vaginalt-fremfall.jpg.asset.json";
import img_gynekologi_vulvalidelser from "@/assets/services/gynekologi-vulvalidelser.jpg.asset.json";
import img_ortopedi_fot_og_ankel from "@/assets/services/ortopedi-fot-og-ankel.jpg.asset.json";
import img_ortopedi_hand_og_albue from "@/assets/services/ortopedi-hand-og-albue.jpg.asset.json";
import img_ortopedi_hero from "@/assets/services/ortopedi-hero.jpg.asset.json";
import img_ortopedi_hofte from "@/assets/services/ortopedi-hofte.jpg.asset.json";
import img_ortopedi_kne from "@/assets/services/ortopedi-kne.jpg.asset.json";
import img_ortopedi_skulder from "@/assets/services/ortopedi-skulder.jpg.asset.json";
import img_urologi_blaere_og_urinveier from "@/assets/urologi/blare-og-urinveier.png.asset.json";
import img_urologi_forhud from "@/assets/urologi/forhud.png.asset.json";
import img_urologi_hero from "@/assets/services/urologi-hero.jpg.asset.json";
import img_urologi_mannlig_infertilitet from "@/assets/urologi/mannlig-infertilitet.png.asset.json";
import img_urologi_nyrer from "@/assets/urologi/nyrer.png.asset.json";
import img_urologi_prostata from "@/assets/urologi/prostata.png.asset.json";
import img_urologi_refertilisering from "@/assets/urologi/refertilisering.png.asset.json";
import img_urologi_robotkirurgi from "@/assets/urologi/robotassistert-kirurgi-1.png.asset.json";
import img_urologi_sterilisering from "@/assets/urologi/sterilisering.png.asset.json";
import img_urologi_testikler_og_pung from "@/assets/urologi/testikler-og-pung.png.asset.json";
import cat_gynekologi from "@/assets/categories/gynekologi.jpg";
import cat_gynekologi_real from "@/assets/categories/gynekologi-real.jpg";
import cat_fertilitet from "@/assets/categories/fertilitet.jpg";
import cat_fertilitet_real from "@/assets/categories/fertilitet-real.jpg";
import cat_ortopedi from "@/assets/categories/ortopedi.jpg";
import cat_ortopedi_real from "@/assets/categories/ortopedi-real.jpg";
import cat_urologi from "@/assets/categories/urologi.jpg";
import cat_urologi_real from "@/assets/categories/urologi-real.jpg";
import cat_flere from "@/assets/categories/flere-fagomrader.jpg";
import hero_pregnancy from "@/assets/hero/hero-pregnancy.jpg";
import hero_technology from "@/assets/hero/hero-technology.jpg";



export const serviceImageBySlug: Record<string, string> = {
  "fertilitet-assistert-befruktning": img_fertilitet_assistert_befruktning.url,
  "fertilitet-donorbehandling": img_fertilitet_donorbehandling.url,
  "fertilitet-eggfrys": img_fertilitet_eggfrys.url,
  "fertilitet-fertilitetsutredning": img_fertilitet_fertilitetsutredning.url,
  "fertilitet-hero": img_fertilitet_hero.url,
  "fertilitet-hysteroskopi": img_fertilitet_hysteroskopi.url,
  "fertilitet-infertilitet": img_fertilitet_infertilitet.url,
  "fertilitet-ivf": img_fertilitet_ivf.url,
  "fertilitet-saedanalyse": img_fertilitet_saedanalyse.url,
  "flere-areknutebehandling": img_flere_areknutebehandling.url,
  "flere-endokrinologi": img_flere_endokrinologi.url,
  "flere-ernaeringsfysologi": img_flere_ernaeringsfysologi.url,
  "flere-gastrokirurgi": img_flere_gastrokirurgi.url,
  "flere-hero": img_flere_hero.url,
  "flere-hudhelse": img_flere_hudhelse.url,
  "flere-hudbehandlinger": img_flere_hudbehandlinger.url,
  "flere-hudpleieprodukter": img_flere_hudpleieprodukter.url,
  "flere-behandlingsutstyr": img_flere_behandlingsutstyr.url,
  "flere-hudlege": img_flere_hudlege.url,
  "flere-osteopati": img_flere_osteopati.url,
  "flere-overvektskirurgi": img_flere_overvektskirurgi.url,
  "flere-brokkoperasjon": img_flere_brokkoperasjon.url,
  "flere-hemorroider-og-endetarmsplager": img_flere_hemorroider.url,
  "flere-plastikkirurgi": img_flere_plastikkirurgi.url,
  "flere-psykologi": img_flere_psykologi.url,
  "flere-revmatologi": img_flere_revmatologi.url,
  "flere-robotkirurgi": img_flere_robotkirurgi.url,
  "flere-sexologi": img_flere_sexologi.url,
  "graviditet-fosterdiagnostikk": img_graviditet_fosterdiagnostikk.url,
  "graviditet-fostermedisin": img_graviditet_fostermedisin.url,
  "graviditet-hero": img_graviditet_hero.url,
  "graviditet-nipt": img_graviditet_nipt.url,
  "graviditet-svangerskapsteam": img_graviditet_svangerskapsteam.url,
  "graviditet-ultralyd": img_graviditet_ultralyd.url,
  "graviditet-6-ukerskontroll": img_graviditet_6_ukerskontroll.url,
  "graviditet-svangerskapsoppfolging": img_gynekologi_graviditet.url,
  "graviditet-fodselsskader": img_gynekologi_fodselsskader.url,
  "graviditet-spontanabort": img_gynekologi_spontanabort.url,
  "gynekologi-blodningsforstyrrelser": img_gynekologi_blodningsforstyrrelser.url,
  "gynekologi-celleforandringer": img_gynekologi_celleforandringer.url,
  "gynekologi-cyster-pa-eggstokkene": img_gynekologi_cyster_pa_eggstokkene.url,
  "gynekologi-endometriose": img_gynekologi_endometriose.url,
  "gynekologi-fjerne-livmor": img_gynekologi_fjerne_livmor.url,
  "gynekologi-graviditet": img_gynekologi_graviditet.url,
  "gynekologi-gynekologisk-kirurgi": img_gynekologi_gynekologisk_kirurgi.url,
  "gynekologi-gynekologisk-undersokelse": img_gynekologi_gynekologisk_undersokelse.url,
  "gynekologi-hero": img_gynekologi_hero.url,
  "gynekologi-hysteroskopi": img_gynekologi_hysteroskopi.url,
  "gynekologi-fodselsskader": img_gynekologi_fodselsskader.url,
  "gynekologi-hormonforstyrrelser": img_gynekologi_hormonforstyrrelser.url,
  "gynekologi-labiaplastikk": img_gynekologi_labiaplastikk.url,
  "gynekologi-overgangsalder": img_gynekologi_overgangsalder.url,
  "gynekologi-robotkirurgi": img_gynekologi_robotkirurgi.url,
  "gynekologi-spontanabort": img_gynekologi_spontanabort.url,
  "gynekologi-tverrfaglig-team": img_gynekologi_tverrfaglig_team.url,
  "gynekologi-urinlekkasje": img_gynekologi_urinlekkasje.url,
  "gynekologi-vaginalt-fremfall": img_gynekologi_vaginalt_fremfall.url,
  "gynekologi-vulvalidelser": img_gynekologi_vulvalidelser.url,
  "ortopedi-fot-og-ankel": img_ortopedi_fot_og_ankel.url,
  "ortopedi-hand-og-albue": img_ortopedi_hand_og_albue.url,
  "ortopedi-hero": img_ortopedi_hero.url,
  "ortopedi-hofte": img_ortopedi_hofte.url,
  "ortopedi-kne": img_ortopedi_kne.url,
  "ortopedi-skulder": img_ortopedi_skulder.url,
  "urologi-blaere-og-urinveier": img_urologi_blaere_og_urinveier.url,
  "urologi-forhud": img_urologi_forhud.url,
  "urologi-hero": img_urologi_hero.url,
  "urologi-mannlig-infertilitet": img_urologi_mannlig_infertilitet.url,
  "urologi-nyrer": img_urologi_nyrer.url,
  "urologi-prostata": img_urologi_prostata.url,
  "urologi-refertilisering": img_urologi_refertilisering.url,
  "urologi-robotkirurgi": img_urologi_robotkirurgi.url,
  "urologi-sterilisering": img_urologi_sterilisering.url,
  "urologi-testikler-og-pung": img_urologi_testikler_og_pung.url,
};

/**
 * Slug aliases — when categoryId+subId routes use a different shape than the
 * uploaded image slugs (e.g. /behandlinger/flere-fagomrader/* uses prefix
 * "flere-fagomrader-" while images use "flere-"), map them here.
 */
const ALIAS: Record<string, string> = {
  // category renames
  "flere-fagomrader": "flere",
};

/**
 * Per-(category,subId) aliases when route slugs differ from image slugs.
 * Key: `${categoryId}/${subId}` (route shape). Value: target subId in images.
 */
const SUB_ALIAS: Record<string, string> = {
  // gynekologi
  "gynekologi/tverrfaglig": "tverrfaglig-team",
  "gynekologi/undersokelse": "gynekologisk-undersokelse",
  "gynekologi/kirurgi": "gynekologisk-kirurgi",
  "gynekologi/vaginale-fremfall": "vaginalt-fremfall",
  "gynekologi/urogynekologi": "vaginalt-fremfall",
  "gynekologi/cyster": "cyster-pa-eggstokkene",
  // NIPT lives in graviditet image set
  // gynekologi pages without dedicated images — reuse closest relevant photo
  "gynekologi/pcos": "hormonforstyrrelser",
  "gynekologi/pms-pmdd": "hormonforstyrrelser",
  // urologi
  "urologi/blaere": "blaere-og-urinveier",
  "urologi/infertilitet": "mannlig-infertilitet",
  "urologi/testikler": "testikler-og-pung",
  // fertilitet
  // ortopedi
  "ortopedi/fot-ankel": "fot-og-ankel",
  "ortopedi/hand-albue": "hand-og-albue",
  // flere-fagomrader (category aliased to "flere")
  "flere-fagomrader/areknuter": "areknutebehandling",
  "flere-fagomrader/ernaringsfysiolog": "ernaeringsfysologi",
  "flere-fagomrader/ernaeringsfysiolog": "ernaeringsfysologi",
  "flere-fagomrader/sleeve-gastrektomi": "overvektskirurgi",
  // fertilitet
  "fertilitet/assistert-befruktning-for-par-og-single": "assistert-befruktning",
  "fertilitet/assistert-befruktning-par-single": "assistert-befruktning",
};

/**
 * Cross-category subId aliases — when an image lives under a different
 * category than the route. Looked up after the in-category SUB_ALIAS miss.
 * Value is the full image slug (e.g. "graviditet-nipt").
 */
const CROSS_CATEGORY_ALIAS: Record<string, string> = {
  "graviditet/fostermedisin": "graviditet-fostermedisin",
};

function normalize(categoryId: string, subId?: string): string {
  const cat = ALIAS[categoryId] ?? categoryId;
  const sub = subId ? (SUB_ALIAS[`${categoryId}/${subId}`] ?? subId) : undefined;
  return sub ? `${cat}-${sub}` : `${cat}-hero`;
}

// ─── Sanity override cache ────────────────────────────────────────────
// Populated at app startup by useServiceImagesSync() (see hooks/useServiceImages.ts).
// Keys: `${categoryId}` for a category hero, `${categoryId}/${subId}` for a
// treatment. When a Sanity image exists it wins; otherwise the CDN pointer
// lookup below runs unchanged.
const sanityImageCache: Record<string, string> = {};

export function setSanityServiceImages(entries: Record<string, string>): void {
  // Replace previous cache to reflect deletions in Sanity.
  for (const k of Object.keys(sanityImageCache)) delete sanityImageCache[k];
  Object.assign(sanityImageCache, entries);
}

function sanityLookup(categoryId: string, subId?: string): string | undefined {
  if (subId) {
    const key = `${categoryId}/${subId}`;
    if (sanityImageCache[key]) return sanityImageCache[key];
  } else {
    if (sanityImageCache[categoryId]) return sanityImageCache[categoryId];
  }
  return undefined;
}

/**
 * Return the CDN URL for a service hero image given the route params.
 * Falls back to the category hero image, then undefined.
 */
export function getServiceImage(categoryId: string, subId?: string): string | undefined {
  const sanity = sanityLookup(categoryId, subId);
  if (sanity) return sanity;
  if (subId) {
    const cross = CROSS_CATEGORY_ALIAS[`${categoryId}/${subId}`];
    if (cross && serviceImageBySlug[cross]) return serviceImageBySlug[cross];
  }
  const exact = serviceImageBySlug[normalize(categoryId, subId)];
  if (exact) return exact;
  // try common slug rewrites
  if (subId) {
    const alt = subId
      .replace(/oe/g, "o")
      .replace(/ae/g, "a")
      .replace(/aa/g, "a");
    const altKey = `${ALIAS[categoryId] ?? categoryId}-${alt}`;
    if (serviceImageBySlug[altKey]) return serviceImageBySlug[altKey];
  }
  // fallback: category hero (Sanity first, then CDN)
  const catSanity = sanityImageCache[ALIAS[categoryId] ?? categoryId] ?? sanityImageCache[categoryId];
  if (catSanity) return catSanity;
  return serviceImageBySlug[`${ALIAS[categoryId] ?? categoryId}-hero`];
}

/**
 * Like getServiceImage, but only returns a URL when a dedicated image
 * exists for the (category, subId) pair. Returns undefined when only the
 * category-level hero would match. Used to override hardcoded fallbacks
 * in static content.
 */
export function getDedicatedServiceImage(categoryId: string, subId?: string): string | undefined {
  if (!subId) return undefined;
  const sanity = sanityLookup(categoryId, subId);
  if (sanity) return sanity;
  const cross = CROSS_CATEGORY_ALIAS[`${categoryId}/${subId}`];
  if (cross && serviceImageBySlug[cross]) return serviceImageBySlug[cross];
  const exact = serviceImageBySlug[normalize(categoryId, subId)];
  if (exact) return exact;
  const alt = subId
    .replace(/oe/g, "o")
    .replace(/ae/g, "a")
    .replace(/aa/g, "a");
  const altKey = `${ALIAS[categoryId] ?? categoryId}-${alt}`;
  return serviceImageBySlug[altKey];
}

export function getCategoryHeroImage(categoryId: string): string | undefined {
  const sanity = sanityImageCache[categoryId] ?? sanityImageCache[ALIAS[categoryId] ?? categoryId];
  if (sanity) return sanity;
  return serviceImageBySlug[`${ALIAS[categoryId] ?? categoryId}-hero`];
}

/**
 * Generic category/stock images used as hero fallbacks in static content.
 * When a page's `heroImage` is one of these it is NOT a dedicated image, so a
 * dedicated asset from serviceImages.ts must win over it.
 */
const GENERIC_IMAGES = new Set<string>([
  cat_gynekologi,
  cat_gynekologi_real,
  cat_fertilitet,
  cat_fertilitet_real,
  cat_ortopedi,
  cat_ortopedi_real,
  cat_urologi,
  cat_urologi_real,
  cat_flere,

  hero_pregnancy,
  hero_technology,
  ...Object.entries(serviceImageBySlug)
    .filter(([slug]) => slug.endsWith("-hero"))
    .map(([, url]) => url),
]);

export function isGenericCategoryImage(url?: string): boolean {
  return !!url && GENERIC_IMAGES.has(url);
}

/**
 * Single resolution order for a treatment page hero AND its cards:
 * 1) the page's own dedicated heroImage (when it is not a generic fallback)
 * 2) the dedicated image in serviceImages.ts for that (category, sub)
 * 3) the category hero as last resort
 */
export function resolveTreatmentImage(
  categoryId: string,
  subId?: string,
  heroImage?: string,
): string | undefined {
  if (heroImage && !isGenericCategoryImage(heroImage)) return heroImage;
  return getDedicatedServiceImage(categoryId, subId) ?? heroImage ?? getServiceImage(categoryId, subId);
}

/**
 * Single source of truth for subpage hero images, resolved from a
 * /behandlinger/<category>/<sub> href. Use on landing pages so service cards
 * show exactly the same image as the subpage hero. Also accepts top-level
 * category routes such as `/graviditet`.
 */
export function getServiceImageFromHref(href: string): string | undefined {
  const clean = href.split(/[?#]/)[0].replace(/\/+$/, "").replace(/^\/+/, "");
  const parts = clean.replace(/^behandlinger\//, "").split("/").filter(Boolean);
  if (parts.length === 0) return undefined;
  // Always resolve from the deepest segment so grouping segments in the URL
  // (e.g. /flere-fagomrader/hudhelse/hudbehandlinger/foflekksjekk) never make a
  // card fall back to the category hero.
  return getServiceImage(parts[0], parts.length > 1 ? parts[parts.length - 1] : undefined);
}


